import math
import random
import time
import requests

BASE_URL = "http://127.0.0.1:8000/api/update-reading/"

# Existing ParticipentCycle IDs
DEVICE_IDS = [1, 2, 3, 4]

t = 0

while True:

    for device in DEVICE_IDS:

        # Simulate rider effort (0 to 1)
        effort = (math.sin(t / 12 + device) + 1) / 2

        # Voltage generated by pedaling
        voltage = round(12 + effort * 28 + random.uniform(-1, 1), 2)

        # Current generated
        amperage = round(0.5 + effort * 5.5 + random.uniform(-0.2, 0.2), 2)

        # Power
        power = round(voltage * amperage, 2)

        payload = {
            "cycle_id": device,
            "voltage": voltage,
            "amperage": amperage,
            "power": power,
        }

        try:
            response = requests.post(
                BASE_URL,
                json=payload,
                # timeout=5,
            )

            print(
                f"Cycle {device} | "
                f"{voltage:.2f} V | "
                f"{amperage:.2f} A | "
                f"{power:.2f} W"
            )

        except Exception as e:
            print(f"Cycle {device}: {e}")

    t += 1
    time.sleep(2)