# Generated by Django 6.0.7 on 2026-07-20 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_no', models.CharField(max_length=100)),
                ('controller_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('dob', models.DateField()),
                ('registered_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipentCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField()),
                ('voltage', models.FloatField()),
                ('amperage', models.FloatField()),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cycle')),
                ('participent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participent')),
            ],
        ),
    ]
