# Generated by Django 6.0.7 on 2026-07-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participentcycle',
            name='amperage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='participentcycle',
            name='power',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='participentcycle',
            name='voltage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
