# Generated by Django 6.0.7 on 2026-07-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_participentcycle_amperage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='controller_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='cycle_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
