# Generated by Django 6.0.7 on 2026-07-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cycle_controller_no_alter_cycle_cycle_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_grouping', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='participentcycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        )
    ]
