# Generated by Django 6.0.7 on 2026-07-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='participentcycle',
            name='total_amperage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='participentcycle',
            name='total_power',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='participentcycle',
            name='total_voltage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
