# Generated by Django 6.0.7 on 2026-07-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_group'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Group',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=100)),
        #         ('members', models.ManyToManyField(related_name='groups', to='core.participentcycle')),
        #     ],
        # ),
    ]
