# Generated by Django 6.0.7 on 2026-07-21 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen_controller.screen')),
            ],
        ),
    ]
