# Generated by Django 6.0.7 on 2026-07-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_controller', '0002_currentscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CurrentScreen',
        ),
    ]
